env:
  IMAGE_REPOSITORY: musashisakamoto/foobar
  KUBECTL_VERSION: "1.14.10"
name: main-workflow
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2-beta
        with:
          go-version: "^1.14"

      - name: Print Go version
        run: go version

      - name: Run unit tests
        run: go test -v ./...

  build-and-release:
    runs-on: ubuntu-latest
    steps:
      # Check out source code.
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Build and push container image
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.IMAGE_REPOSITORY }}
          tag_with_ref: true
          tag_with_sha: true # sha-${GITHUB_SHA::7}

  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs:
      - run-tests
      - build-and-release
    steps:
      # Check out source code.
      - name: Check out source code
        uses: actions/checkout@v2
      # Set up kubectl.
      - name: Set up kubectl
        run: |-
          curl -sfLo kubectl https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/
